<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Определяем свойства, которые будут использоваться в этом файле -->
  <xacro:property name="body_radius" value="0.25"/>
  <xacro:property name="wheel_radius" value="0.08"/>

  <!-- Камера глубины -->
  <gazebo reference="depth_frame">
    <sensor name="depth_camera" type="depth">
      <always_on>true</always_on>
      <update_rate>30.0</update_rate>
      <camera name="camera">
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>10.0</far>
        </clip>
      </camera>
      <plugin name="gz::sim::systems::DepthCamera" filename="gz-sim-depth-camera-system">
        <alwaysOn>true</alwaysOn>
        <updateRate>30.0</updateRate>
        <cameraName>camera/depth</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>depth_frame</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- IMU -->
  <gazebo reference="imu_link">
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>imu</topic>
      <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu">
        <topicName>imu</topicName>
        <bodyName>imu_link</bodyName>
        <updateRateHZ>100.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Плагин дифференциального привода для ведущих колес -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>drive_wheel_left_joint</left_joint>
      <right_joint>drive_wheel_right_joint</right_joint>
      <wheel_separation>${2.4 * body_radius}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>30</odom_publish_frequency>
      <!-- <topic>cmd_vel</topic> -->
      <!-- <odom_topic>odometry</odom_topic> -->
      <!-- <odom_frame>odom</odom_frame> -->
      <!-- <robot_base_frame>base_link</robot_base_frame>
      <odometry_source>world</odometry_source> -->
      <child_frame_id>robot/base_link</child_frame_id>
      <max_linear_velocity>2.0</max_linear_velocity>
      <max_angular_velocity>3.0</max_angular_velocity>
    </plugin>
  </gazebo>

  <!-- Плагин для публикации состояний шарниров -->
  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <!-- <joint_name>drive_wheel_left_joint</joint_name>
      <joint_name>drive_wheel_right_joint</joint_name>
      <joint_name>front_right_x_joint</joint_name>
      <joint_name>front_left_x_joint</joint_name>
      <joint_name>rear_right_x_joint</joint_name>
      <joint_name>rear_left_x_joint</joint_name> -->
      <!-- <topic>joint_states</topic> -->
      <update_rate>30</update_rate>
    </plugin>
  </gazebo>

  <!-- Физические свойства для основного тела -->
  <gazebo reference="base_link">
    <material>Gazebo/Brown</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
    <mu1>0.8</mu1>
    <mu2>0.8</mu2>
    <kp>1000000.0</kp>
    <kd>1000.0</kd>
  </gazebo>

  <!-- Ведущие колеса -->
  <gazebo reference="drive_wheel_left">
    <material>Gazebo/Red</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
    <mu1>2.0</mu1>
    <mu2>2.0</mu2>
    <kp>1000000.0</kp>
    <kd>1000.0</kd>
  </gazebo>

  <gazebo reference="drive_wheel_right">
    <material>Gazebo/Red</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
    <mu1>2.0</mu1>
    <mu2>2.0</mu2>
    <kp>1000000.0</kp>
    <kd>1000.0</kd>
  </gazebo>

  <!-- Сферические колеса -->
  <gazebo reference="front_right_wheel">
    <material>Gazebo/DarkGrey</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
    <mu1>0.01</mu1>
    <mu2>0.01</mu2>
    <kp>1000000.0</kp>
    <kd>1000.0</kd>
    <surface>
      <friction>
        <ode>
          <mu>0.01</mu>
          <mu2>0.01</mu2>
          <slip1>0.1</slip1>
          <slip2>0.1</slip2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <gazebo reference="front_left_wheel">
    <material>Gazebo/DarkGrey</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
    <mu1>0.01</mu1>
    <mu2>0.01</mu2>
    <kp>1000000.0</kp>
    <kd>1000.0</kd>
    <surface>
      <friction>
        <ode>
          <mu>0.01</mu>
          <mu2>0.01</mu2>
          <slip1>0.1</slip1>
          <slip2>0.1</slip2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <gazebo reference="rear_right_wheel">
    <material>Gazebo/DarkGrey</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
    <mu1>0.01</mu1>
    <mu2>0.01</mu2>
    <kp>1000000.0</kp>
    <kd>1000.0</kd>
    <surface>
      <friction>
        <ode>
          <mu>0.01</mu>
          <mu2>0.01</mu2>
          <slip1>0.1</slip1>
          <slip2>0.1</slip2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <gazebo reference="rear_left_wheel">
    <material>Gazebo/DarkGrey</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
    <mu1>0.01</mu1>
    <mu2>0.01</mu2>
    <kp>1000000.0</kp>
    <kd>1000.0</kd>
    <surface>
      <friction>
        <ode>
          <mu>0.01</mu>
          <mu2>0.01</mu2>
          <slip1>0.1</slip1>
          <slip2>0.1</slip2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <!-- Голова -->
  <gazebo reference="head_link">
    <material>Gazebo/Tan</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>

  <!-- Иголки -->
  <gazebo reference="spike_0">
    <material>Gazebo/DarkBrown</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>
  <gazebo reference="spike_1">
    <material>Gazebo/DarkBrown</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>
  <gazebo reference="spike_2">
    <material>Gazebo/DarkBrown</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>
  <gazebo reference="spike_3">
    <material>Gazebo/DarkBrown</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>
  <gazebo reference="spike_4">
    <material>Gazebo/DarkBrown</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>
  <gazebo reference="spike_5">
    <material>Gazebo/DarkBrown</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>
  <gazebo reference="spike_6">
    <material>Gazebo/DarkBrown</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>
  <gazebo reference="spike_7">
    <material>Gazebo/DarkBrown</material>
    <selfCollide>false</selfCollide>
    <gravity>true</gravity>
  </gazebo>

</robot>